In [1]:
import numpy as np
import pandas as pd

In [7]:
countries = pd.read_csv("HNP_StatsCountry-Series.csv")
country_stats = pd.read_csv("HNP_StatsCountry.csv")
stats_data = pd.read_csv("HNP_StatsData.csv")
stats_footnotes = pd.read_csv("HNP_StatsFootNote.csv")
stats_seriestime = pd.read_csv("HNP_StatsSeries-Time.csv")
stats_series = pd.read_csv("HNP_StatsSeries.csv")

In [8]:
countries

,CountryCode,SeriesCode,DESCRIPTION,Unnamed: 3
0,ABW,SP.DYN.AMRT.MA,Data source: United Nations World Population P...,NaN
1,ABW,SP.DYN.LE00.MA.IN,Data source: United Nations World Population P...,NaN
2,ABW,SP.DYN.CDRT.IN,Data source: United Nations World Population P...,NaN
3,ABW,SP.DYN.AMRT.FE,Data source: United Nations World Population P...,NaN
4,ABW,SM.POP.NETM,Data source: United Nations World Population P...,NaN
...,...,...,...,...
3363,ZWE,SP.DYN.LE00.MA.IN,Data source: United Nations World Population P...,NaN
3364,ZWE,SP.DYN.CBRT.IN,Data source: United Nations World Population P...,NaN
3365,ZWE,SP.DYN.AMRT.FE,Data source: United Nations World Population P...,NaN
3366,ZWE,SP.POP.TOTL,Data source: United Nations World Population P...,NaN
3367,ZWE,SP.DYN.AMRT.MA,Data source: United Nations World Population P...,NaN

In [9]:
country_stats

,Country Code,Short Name,Table Name,Long Name,2-alpha code,Currency Unit,Special Notes,Region,Income Group,WB-2 code,...,Government Accounting concept,IMF data dissemination standard,Latest population census,Latest household survey,Source of most recent Income and expenditure data,Vital registration complete,Latest agricultural census,Latest industrial data,Latest trade data,Unnamed: 30
0,ABW,Aruba,Aruba,Aruba,AW,Aruban florin,NaN,Latin America & Caribbean,High income,AW,...,NaN,Enhanced General Data Dissemination System (e-...,2010,NaN,NaN,Yes,NaN,NaN,2016.0,NaN
1,AFG,Afghanistan,Afghanistan,Islamic State of Afghanistan,AF,Afghan afghani,NaN,South Asia,Low income,AF,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,1979,"Demographic and Health Survey, 2015","Integrated household survey (IHS), 2016/17",NaN,NaN,NaN,2017.0,NaN
2,AGO,Angola,Angola,People's Republic of Angola,AO,Angolan kwanza,NaN,Sub-Saharan Africa,Lower middle income,AO,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2014,"Demographic and Health Survey, 2015/16","Integrated household survey (IHS), 2008/09",NaN,NaN,NaN,2017.0,NaN
3,ALB,Albania,Albania,Republic of Albania,AL,Albanian lek,NaN,Europe & Central Asia,Upper middle income,AL,...,Consolidated central government,Enhanced General Data Dissemination System (e-...,2011,"Demographic and Health Survey, 2017/18",Living Standards Measurement Study Survey (LSM...,Yes,2012,2013.0,2017.0,NaN
4,AND,Andorra,Andorra,Principality of Andorra,AD,Euro,NaN,Europe & Central Asia,High income,AD,...,NaN,NaN,2011. Population data compiled from administra...,NaN,NaN,Yes,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253,XKX,Kosovo,Kosovo,Republic of Kosovo,XK,Euro,NaN,Europe & Central Asia,Upper middle income,XK,...,NaN,Enhanced General Data Dissemination System (e-...,2011,"Multiple Indicator Cluster Survey, 2013/14","Expenditure survey/budget survey (ES/BS), 2015",NaN,2014,NaN,NaN,NaN
254,YEM,Yemen,"Yemen, Rep.",Republic of Yemen,YE,Yemeni rial,NaN,Middle East & North Africa,Low income,RY,...,NaN,Enhanced General Data Dissemination System (e-...,2004,"Demographic and Health Survey, 2013","Expenditure survey/budget survey (ES/BS), 2014",NaN,NaN,2012.0,2017.0,NaN
255,ZAF,South Africa,South Africa,Republic of South Africa,ZA,South African rand,Fiscal year end: March 31; reporting period fo...,Sub-Saharan Africa,Upper middle income,ZA,...,Consolidated central government,Special Data Dissemination Standard (SDDS),2011,"Demographic and Health Survey, 2016","Expenditure survey/budget survey (ES/BS), 2014/15",NaN,2007,2010.0,2017.0,NaN
256,ZMB,Zambia,Zambia,Republic of Zambia,ZM,New Zambian kwacha,National accounts data were rebased to reflect...,Sub-Saharan Africa,Lower middle income,ZM,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2010,"Demographic and Health Survey, 2018","Integrated household survey (IHS), 2015",NaN,NaN,1994.0,2017.0,NaN
257,ZWE,Zimbabwe,Zimbabwe,Republic of Zimbabwe,ZW,U.S. dollar,NaN,Sub-Saharan Africa,Lower middle income,ZW,...,Budgetary central government,Enhanced General Data Dissemination System (e-...,2012,"Multiple Indicator Cluster Survey, 2019","Integrated household survey (IHS), 2011/12",NaN,NaN,NaN,2017.0,NaN

In [18]:
stats_data

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,Unnamed: 65
0,Arab World,ARB,"Adolescent fertility rate (births per 1,000 wo...",SP.ADO.TFRT,134.772341,135.343859,136.030214,135.898025,135.721826,135.387563,...,49.790826,49.344963,48.853665,48.279737,47.505489,46.688851,46.005049,NaN,NaN,NaN
1,Arab World,ARB,Adults (ages 15+) and children (0-14 years) li...,SH.HIV.TOTL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Arab World,ARB,Adults (ages 15+) and children (ages 0-14) new...,SH.HIV.INCD.TL,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Arab World,ARB,Adults (ages 15+) living with HIV,SH.DYN.AIDS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Arab World,ARB,Adults (ages 15-49) newly infected with HIV,SH.HIV.INCD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109293,Zimbabwe,ZWE,Wanted fertility rate (births per woman),SP.DYN.WFRT,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.600000,NaN,NaN,NaN,NaN,NaN,NaN
109294,Zimbabwe,ZWE,Women who were first married by age 15 (% of w...,SP.M15.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,5.4,NaN,NaN
109295,Zimbabwe,ZWE,Women who were first married by age 18 (% of w...,SP.M18.2024.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,33.500000,32.400000,NaN,NaN,NaN,33.7,NaN,NaN
109296,Zimbabwe,ZWE,Women's share of population ages 15+ living wi...,SH.DYN.AIDS.FE.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,59.200000,59.300000,59.400000,59.400000,59.500000,59.500000,59.600000,59.6,NaN,NaN
109297,Zimbabwe,ZWE,Young people (ages 15-24) newly infected with HIV,SH.HIV.INCD.YG,NaN,NaN,NaN,NaN,NaN,NaN,...,21000.000000,20000.000000,19000.000000,18000.000000,16000.000000,15000.000000,13000.000000,13000.0,NaN,NaN

In [11]:
stats_footnotes

,CountryCode,SeriesCode,Year,DESCRIPTION,Unnamed: 4
0,ABW,SE.ADT.LITR.ZS,YR2018,UIS Estimation,NaN
1,ABW,SE.ADT.LITR.MA.ZS,YR2018,UIS Estimation,NaN
2,ABW,SP.DYN.SMAM.FE,YR2010,Source: Aruba 2010 Census.,NaN
3,ABW,SP.DYN.SMAM.FE,YR2000,Source: Aruba 2000 Census.,NaN
4,ABW,SP.DYN.SMAM.FE,YR1991,Source: Aruba 1991 Census.,NaN
...,...,...,...,...,...
443055,ZWE,SH.HIV.INCD.50.P3,YR2002,Plausible bound is 1.94 - 7.84,NaN
443056,ZWE,SH.HIV.INCD.50.P3,YR2001,Plausible bound is 2.12 - 8.56,NaN
443057,ZWE,SH.HIV.INCD.50.P3,YR2000,Plausible bound is 2.35 - 9.48,NaN
443058,ZWE,SH.HIV.INCD.50.P3,YR1999,Plausible bound is 2.69 - 10.84,NaN
443059,ZWE,SH.HIV.INCD.50.P3,YR1998,Plausible bound is 3.09 - 12.47,NaN

In [12]:
stats_seriestime

,SeriesCode,Year,DESCRIPTION,Unnamed: 3
0,SP.ADO.TFRT,YR1960,Interpolated using data for 1957 and 1962.,NaN
1,SP.DYN.TO65.FE.ZS,YR1960,Interpolated using data for 1957 and 1962.,NaN
2,SP.DYN.TO65.MA.ZS,YR1960,Interpolated using data for 1957 and 1962.,NaN
3,SP.DYN.AMRT.FE,YR1960,"Interpolated using data for 1957 and 1962, if ...",NaN
4,SP.DYN.AMRT.MA,YR1960,"Interpolated using data for 1957 and 1962, if ...",NaN
...,...,...,...,...
415,SP.ADO.TFRT,YR2018,Interpolated using data for 2017 and 2022,NaN
416,SP.POP.BRTH.MF,YR2018,Interpolated using data for 2017 and 2022.,NaN
417,SH.MLR.IPTP.ZS,YR2018,Averages for regions/groups are based on most ...,NaN
418,SH.MLR.NETS.ZS,YR2018,Averages for regions/groups are based on most ...,NaN
419,SP.DYN.TO65.FE.ZS,YR2018,Interpolated using data for 2017 and 2022.,NaN

In [13]:
stats_series

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,...,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type,Unnamed: 20
0,HD.HCI.OVRL,Public Sector: Policy & institutions,Human capital index (HCI) (scale 0-1),NaN,The HCI calculates the contributions of health...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,World Bank staff calculations based on the met...,NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
1,HD.HCI.OVRL.FE,Public Sector: Policy & institutions,"Human capital index (HCI), female (scale 0-1)",NaN,The HCI calculates the contributions of health...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,World Bank staff calculations based on the met...,NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
2,HD.HCI.OVRL.LB,Public Sector: Policy & institutions,"Human capital index (HCI), lower bound (scale ...",NaN,The HCI lower bound reflects uncertainty in th...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,World Bank staff calculations based on the met...,NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
3,HD.HCI.OVRL.LB.FE,Public Sector: Policy & institutions,"Human capital index (HCI), female, lower bound...",NaN,The HCI lower bound reflects uncertainty in th...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,World Bank staff calculations based on the met...,NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
4,HD.HCI.OVRL.LB.MA,Public Sector: Policy & institutions,"Human capital index (HCI), male, lower bound (...",NaN,The HCI lower bound reflects uncertainty in th...,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,World Bank staff calculations based on the met...,NaN,NaN,NaN,NaN,NaN,CC BY-4.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
417,SP.RUR.TOTL.ZS,Environment: Density & urbanization,Rural population (% of total population),NaN,Rural population refers to people living in ru...,NaN,Annual,NaN,NaN,Weighted average,...,NaN,NaN,World Bank staff estimates based on the United...,Rural population is calculated as the differen...,The rural population is calculated using the u...,NaN,NaN,NaN,CC BY-4.0,NaN
418,SP.URB.GROW,Environment: Density & urbanization,Urban population growth (annual %),NaN,Urban population refers to people living in ur...,NaN,Annual,NaN,NaN,Weighted average,...,NaN,NaN,World Bank staff estimates based on the United...,Urban population refers to people living in ur...,Explosive growth of cities globally signifies ...,NaN,NaN,NaN,CC BY-4.0,NaN
419,SP.URB.TOTL,Environment: Density & urbanization,Urban population,NaN,Urban population refers to people living in ur...,NaN,Annual,NaN,NaN,Sum,...,NaN,NaN,World Bank staff estimates based on the United...,Urban population refers to people living in ur...,Explosive growth of cities globally signifies ...,NaN,NaN,NaN,CC BY-4.0,NaN
420,SP.URB.TOTL.IN.ZS,Environment: Density & urbanization,Urban population (% of total population),NaN,Urban population refers to people living in ur...,NaN,Annual,NaN,NaN,Weighted average,...,NaN,NaN,United Nations Population Division. World Urba...,Urban population refers to people living in ur...,Explosive growth of cities globally signifies ...,NaN,NaN,NaN,CC BY-4.0,NaN
421,SP.UWT.TFRT,Health: Reproductive health,Unmet need for contraception (% of married wom...,NaN,Unmet need for contraception is the percentage...,NaN,Annual,NaN,NaN,Weighted Average,...,NaN,Unmet need for contraception measures the capa...,"Household surveys, including Demographic and H...",Reproductive health is a state of physical and...,NaN,NaN,NaN,NaN,CC BY-4.0,NaN